### ISSUE TITLE
Suggest to loosen the dependency on halo

### ISSUE THREAD

**Issue by Agnes-U** [MedAmineFouzai/WADOG2#3]
Hi, your project WADOG2(commit id: f7f95511b60f16b06ca360600c018ced030e9a65) requires "halo==0.0.29" in its dependency. After analyzing the source code, we found that the following versions of halo can also be suitable, i.e., halo 0.0.28, since all functions that you directly (4 APIs: halo.halo.Halo.succeed, halo.halo.Halo.start, halo.halo.Halo.__init__, halo.halo.Halo.info) or indirectly (propagate to 14 halo's internal APIs and 9 outsider APIs) used from the package have not been changed in these versions, thus not affecting your usage.

Therefore, we believe that it is quite safe to loose your dependency on halo from "halo==0.0.29" to "halo>=0.0.28,<=0.0.29". This will improve the applicability of WADOG2 and reduce the possibility of any further dependency conflict with other projects. 

May I pull a request to further loosen the dependency on halo?

By the way, could you please tell us whether such an automatic tool for dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

**Comment by AmineFouzai** [comment]
ok thaks for your ,you can make a pull request ,on the subject ,develoment well be back soon ,asap when i find time for it ,for now i will push the dependency
